python DeathKnightParse.py
python DeathKnightParseLegendarys.py
python DemonHunterParse.py
python DemonHunterParseLegendarys.py
python DruidParse.py
python DruidParseLegendarys.py
python HunterParse.py
python HunterParseLegendarys.py
python MageParse.py
python MageParseLegendarys.py
python MonkParse.py
python MonkParseLegendarys.py
python PaladinParse.py
python PaladinParseLegendarys.py
python PriestParse.py
python PriestParseLegendarys.py
python RogueParse.py
python RogueParseLegendarys.py
python ShamanParse.py
python ShamanParseLegendarys.py
python WarlockParse.py
python WarlockParseLegendarys.py
python WarriorParse.py
python WarriorParseLegendarys.py